version: '3.8'

services:
  product-postgres:
    image: postgres
    container_name: product-postgres
    read_only: true
    environment:
      - POSTGRES_USER=ndmkcn
      - POSTGRES_PASSWORD=Erdem123.
      - POSTGRES_DB=productDB
    expose:
      - '5490'
    ports:
      - '5490:5490'
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    volumes:
      - product-volume:/var/lib/postgresql/data
    command: -p 5490
volumes:
  product-volume: